name: Go Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: |
          mkdir -p bin
          go build -o bin/dvpl_lz4-linux

      - name: Run tests
        run: go test ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dvpl_lz4-linux
          path: bin/dvpl_lz4-linux

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: |
          mkdir -p bin
          go build -o bin/dvpl_lz4-windows.exe

      - name: Run tests
        run: go test ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dvpl_lz4-windows
          path: bin/dvpl_lz4-windows.exe
